version: '3.6'

networks:
  ollama:

services:
  ollama:
    image: ollama/ollama
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    volumes:
      - ./data/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3002:8080
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama

  ios_xe_buddy:
    image: johncapobianco/ios_xe_buddy:ios_xe_buddy
    container_name: ios_xe_buddy
    restart: always     
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile
    ports:
      - "8502:8502"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - ollama
    volumes:
      - ./config.toml:/root/.streamlit/config.toml      
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]       